import type Rom from "../types/rom";

const blitz: Rom = {
  controlGroups: {},
  data: "EhdCTElUWiBCeSBEYXZpZCBXSU5URVKjQWAEYQliDmcE0B7yHnAMMEASIfAKAOAi2fAKAOCOcKMeax/MH4zE3LI/ARJJ3LISOcoHegF7/tyyev86ABJNfv8+ABI5awCMcG0AbgCjG93jPwASwTsAEoFgBeCeEodrAYjQeAKJ4HkDox7YkYHwYAXwFfAHMAASizsBEqujHjEB2JF5ATkgEqtrADEAfP9MABK7oxvd430CPUASuW0AfgESZQDgdwISLaMb3eNgFGECYgujINAb8h5wCDAsEs0S12AKYQ1iBaMH0BXyHnAIMCoS4YBwcP6ABqOH8DPyZWAt8SlhDdAVcAXyKdAVAO6DgoOC++gIiAXivqC4ID6AgICA+ID4/MDA+YHby/sA+oqamfjvKugpKQBvaC5Mj76guLC+AL4iPjSy2NgAw8MA2NgAw8MA2NjAwADAwADAwADAwADb29vbABgYABgYABgYANvb29sAGBgAGBgAGBgAGBjb2wADAwAYGADAwADb2w==",
  name: "Blitz",
};
export default blitz;
